/** Czech name-day and public-holiday messages indexed by month, then day. */
export const nameDayMessages: readonly (readonly string[])[] = [
	[
		'Je Nový rok, Den obnovy samostatného českého státu',
		'Svátek má Karina',
		'Svátek má Radmila',
		'Svátek má Diana',
		'Svátek má Dalimil',
		'Je den Tří králů',
		'Svátek má Vilma',
		'Svátek má Čestmír',
		'Svátek má Vladan',
		'Svátek má Břetislav',
		'Svátek má Bohdana',
		'Svátek má Pravoslav',
		'Svátek má Edita',
		'Svátek má Radovan',
		'Svátek má Alice',
		'Svátek má Ctirad',
		'Svátek má Drahoslav',
		'Svátek má Vladislav',
		'Svátek má Doubravka',
		'Svátek má Ilona',
		'Svátek má Běla',
		'Svátek má Slavomír',
		'Svátek má Zdeněk',
		'Svátek má Milena',
		'Svátek má Miloš',
		'Svátek má Zora',
		'Svátek má Ingrid',
		'Svátek má Otýlie',
		'Svátek má Zdislava',
		'Svátek má Robin',
		'Svátek má Marika',
	],
	[
		'Svátek má Hynek',
		'Svátek má Nela',
		'Svátek má Blažej',
		'Svátek má Jarmila',
		'Svátek má Dobromila',
		'Svátek má Vanda',
		'Svátek má Veronika',
		'Svátek má Milada',
		'Svátek má Apolena',
		'Svátek má Mojmír',
		'Svátek má Božena',
		'Svátek má Slavěna',
		'Svátek má Věnceslav',
		'Svátek má Valentýn',
		'Svátek má Jiřina',
		'Svátek má Ljuba',
		'Svátek má Miloslava',
		'Svátek má Gizela',
		'Svátek má Patrik',
		'Svátek má Oldřich',
		'Svátek má Lenka',
		'Svátek má Petr',
		'Svátek má Svatopluk',
		'Svátek má Matěj',
		'Svátek má Liliana',
		'Svátek má Dorota',
		'Svátek má Alexandr',
		'Svátek má Lumír',
		'Svátek má Horymír',
	],
	[
		'Svátek má Bedřich',
		'Svátek má Anežka',
		'Svátek má Kamil',
		'Svátek má Stela',
		'Svátek má Kazimír',
		'Svátek má Miroslav',
		'Svátek má Tomáš',
		'Svátek má Gabriela',
		'Svátek má Františka',
		'Svátek má Viktorie',
		'Svátek má Anděla',
		'Svátek má Řehoř',
		'Svátek má Růžena',
		'Svátek má Rút a Matylda',
		'Svátek má Ida',
		'Svátek má Elena a Herbert',
		'Svátek má Vlastimil',
		'Svátek má Eduard',
		'Svátek má Josef',
		'Svátek má Světlana',
		'Svátek má Radek',
		'Svátek má Leona',
		'Svátek má Ivona',
		'Svátek má Gabriel',
		'Svátek má Marián',
		'Svátek má Emanuel',
		'Svátek má Dita',
		'Svátek má Soňa',
		'Svátek má Taťána',
		'Svátek má Arnošt',
		'Svátek má Kvido',
	],
	[
		'Svátek má Hugo',
		'Svátek má Erika',
		'Svátek má Richard',
		'Svátek má Ivana',
		'Svátek má Miroslava',
		'Svátek má Vendula',
		'Svátek má Heřman a Hermína',
		'Svátek má Ema',
		'Svátek má Dušan',
		'Svátek má Darja',
		'Svátek má Izabela',
		'Svátek má Julius',
		'Svátek má Aleš',
		'Svátek má Vincenc',
		'Svátek má Anastázie',
		'Svátek má Irena',
		'Svátek má Rudolf',
		'Svátek má Valérie',
		'Svátek má Rostislav',
		'Svátek má Marcela',
		'Svátek má Alexandra',
		'Svátek má Evženie',
		'Svátek má Vojtěch',
		'Svátek má Jiří',
		'Svátek má Marek',
		'Svátek má Oto',
		'Svátek má Jaroslav',
		'Svátek má Vlastislav',
		'Svátek má Robert',
		'Svátek má Blahoslav',
	],
	[
		'Je Svátek práce',
		'Svátek má Zikmund',
		'Svátek má Alexej',
		'Svátek má Květoslav',
		'Svátek má Klaudie',
		'Svátek má Radoslav',
		'Svátek má Stanislav',
		'Je Den vítězství',
		'Svátek má Ctibor',
		'Svátek má Blažena',
		'Svátek má Svatava',
		'Svátek má Pankrác',
		'Svátek má Servác',
		'Svátek má Bonifác',
		'Svátek má Žofie',
		'Svátek má Přemysl',
		'Svátek má Aneta',
		'Svátek má Nataša',
		'Svátek má Ivo',
		'Svátek má Zbyšek',
		'Svátek má Monika',
		'Svátek má Emil',
		'Svátek má Vladimír',
		'Svátek má Jana',
		'Svátek má Viola',
		'Svátek má Filip',
		'Svátek má Valdemar',
		'Svátek má Vilém',
		'Svátek má Maxmilián',
		'Svátek má Ferdinand',
		'Svátek má Kamila',
	],
	[
		'Svátek má Laura',
		'Svátek má Jarmil',
		'Svátek má Tamara',
		'Svátek má Dalibor',
		'Svátek má Dobroslav',
		'Svátek má Norbert',
		'Svátek má Iveta a Slavoj',
		'Svátek má Medard',
		'Svátek má Stanislava',
		'Svátek má Gita',
		'Svátek má Bruno',
		'Svátek má Antonie',
		'Svátek má Antonín',
		'Svátek má Roland',
		'Svátek má Vít',
		'Svátek má Zbyněk',
		'Svátek má Adolf',
		'Svátek má Milan',
		'Svátek má Leoš',
		'Svátek má Květa',
		'Svátek má Alois',
		'Svátek má Pavla',
		'Svátek má Zdeňka',
		'Svátek má Jan',
		'Svátek má Ivan',
		'Svátek má Adriana',
		'Svátek má Ladislav',
		'Svátek má Lubomír',
		'Svátek má Petr a Pavel',
		'Svátek má Šárka',
	],
	[
		'Svátek má Jaroslava',
		'Svátek má Patricie',
		'Svátek má Radomír',
		'Svátek má Prokop',
		'Svátek má Cyril a Metoděj',
		'Je Den upálení mistra Jana Husa',
		'Svátek má Bohuslava',
		'Svátek má Nora',
		'Svátek má Drahoslava',
		'Svátek má Libuše a Amálie',
		'Svátek má Olga',
		'Svátek má Bořek',
		'Svátek má Markéta',
		'Svátek má Karolína',
		'Svátek má Jindřich',
		'Svátek má Luboš',
		'Svátek má Martina',
		'Svátek má Drahomíra',
		'Svátek má Čeněk',
		'Svátek má Ilja',
		'Svátek má Vítězslav',
		'Svátek má Magdaléna',
		'Svátek má Libor',
		'Svátek má Kristýna',
		'Svátek má Jakub',
		'Svátek má Anna',
		'Svátek má Věroslav',
		'Svátek má Viktor',
		'Svátek má Marta',
		'Svátek má Bořivoj',
		'Svátek má Ignác',
	],
	[
		'Svátek má Oskar',
		'Svátek má Gustav',
		'Svátek má Miluše',
		'Svátek má Dominik',
		'Svátek má Kristián',
		'Svátek má Oldřiška',
		'Svátek má Lada',
		'Svátek má Soběslav',
		'Svátek má Roman',
		'Svátek má Vavřinec',
		'Svátek má Zuzana',
		'Svátek má Klára',
		'Svátek má Alena',
		'Svátek má Alan',
		'Svátek má Hana',
		'Svátek má Jáchym',
		'Svátek má Petra',
		'Svátek má Helena',
		'Svátek má Ludvík',
		'Svátek má Bernard',
		'Svátek má Johana',
		'Svátek má Bohuslav',
		'Svátek má Sandra',
		'Svátek má Bartoloměj',
		'Svátek má Radim',
		'Svátek má Luděk',
		'Svátek má Otakar',
		'Svátek má Augustýn',
		'Svátek má Evelína',
		'Svátek má Vladěna',
		'Svátek má Pavlína',
	],
	[
		'Svátek má Linda a Samuel',
		'Svátek má Adéla',
		'Svátek má Bronislav',
		'Svátek má Jindřiška',
		'Svátek má Boris',
		'Svátek má Boleslav',
		'Svátek má Regína',
		'Svátek má Mariana',
		'Svátek má Daniela',
		'Svátek má Irma',
		'Svátek má Denisa',
		'Svátek má Marie',
		'Svátek má Lubor',
		'Svátek má Radka',
		'Svátek má Jolana',
		'Svátek má Ludmila',
		'Svátek má Naděžda',
		'Svátek má Kryštof',
		'Svátek má Zita',
		'Svátek má Oleg',
		'Svátek má Matouš',
		'Svátek má Darina',
		'Svátek má Berta',
		'Svátek má Jaromír',
		'Svátek má Zlata',
		'Svátek má Andrea',
		'Svátek má Jonáš',
		'Svátek má Václav, je Den české státnosti',
		'Svátek má Michal',
		'Svátek má Jeroným',
	],
	[
		'Svátek má Igor',
		'Svátek má Olivie a Oliver',
		'Svátek má Bohumil',
		'Svátek má František',
		'Svátek má Eliška',
		'Svátek má Hanuš',
		'Svátek má Justýna',
		'Svátek má Věra',
		'Svátek má Štefan a Sára',
		'Svátek má Marina',
		'Svátek má Andrej',
		'Svátek má Marcel',
		'Svátek má Renáta',
		'Svátek má Agáta',
		'Svátek má Tereza',
		'Svátek má Havel',
		'Svátek má Hedvika',
		'Svátek má Lukáš',
		'Svátek má Michaela',
		'Svátek má Vendelín',
		'Svátek má Brigita',
		'Svátek má Sabina',
		'Svátek má Teodor',
		'Svátek má Nina',
		'Svátek má Beáta',
		'Svátek má Erik',
		'Svátek má Šarlota a Zoe',
		'Je Den vzniku samostatného československého státu',
		'Svátek má Silvie',
		'Svátek má Tadeáš',
		'Svátek má Štěpánka',
	],
	[
		'Svátek má Felix',
		'Je Památka zesnulých',
		'Svátek má Hubert',
		'Svátek má Karel',
		'Svátek má Miriam',
		'Svátek má Liběna',
		'Svátek má Saskie',
		'Svátek má Bohumír',
		'Svátek má Bohdan',
		'Svátek má Evžen',
		'Svátek má Martin',
		'Svátek má Benedikt',
		'Svátek má Tibor',
		'Svátek má Sáva',
		'Svátek má Leopold',
		'Svátek má Otmar',
		'Svátek má Mahulena, je Den boje za svobodu a demokracii',
		'Svátek má Romana',
		'Svátek má Alžběta',
		'Svátek má Nikola',
		'Svátek má Albert',
		'Svátek má Cecílie',
		'Svátek má Klement',
		'Svátek má Emílie',
		'Svátek má Kateřina',
		'Svátek má Artur',
		'Svátek má Xenie',
		'Svátek má René',
		'Svátek má Zina',
		'Svátek má Ondřej',
	],
	[
		'Svátek má Iva',
		'Svátek má Blanka',
		'Svátek má Svatoslav',
		'Svátek má Barbora',
		'Svátek má Jitka',
		'Svátek má Mikuláš',
		'Svátek má Benjamín',
		'Svátek má Květoslava',
		'Svátek má Vratislav',
		'Svátek má Julie',
		'Svátek má Dana',
		'Svátek má Simona',
		'Svátek má Lucie',
		'Svátek má Lýdie',
		'Svátek má Radana',
		'Svátek má Albína',
		'Svátek má Daniel',
		'Svátek má Miloslav',
		'Svátek má Ester',
		'Svátek má Dagmar',
		'Svátek má Natálie',
		'Svátek má Šimon',
		'Svátek má Vlasta',
		'Svátek má Adam a Eva, je Štědrý den',
		'Je 1. svátek vánoční',
		'Svátek má Štěpán, je 2. svátek vánoční',
		'Svátek má Žaneta',
		'Svátek má Bohumila',
		'Svátek má Judita',
		'Svátek má David',
		'Svátek má Silvestr',
	],
];
